micronaut:
  application:
    name: backend
  session:
    http:
      cookie: true
      header: true
      redis:
        enabled: true
redis.uri: redis://localhost
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
